# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.

---

include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - always_declare_return_types

analyzer:
  exclude: lib/templates/*.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false